![Factories creating emissions](pollution.jpg)

Foto de Maxim Tolchinskiy en Unsplash
  
Si tenemos en cuenta el calor necesario para la fabricación y el transporte de productos, _las emisiones de gases de efecto invernadero atribuibles a los productos —desde alimentos hasta zapatillas o electrodomésticos— representan más del 75 % de las emisiones globales._ (`Fuente: The Carbon Catalogue https://www.nature.com/articles/s41597-022-01178-9`)

Nuestros datos, disponibles públicamente en nature.com, contienen las huellas de carbono de productos (PCF, por sus siglas en inglés) de varias empresas. Las PCF son las emisiones de gases de efecto invernadero atribuibles a un producto concreto, medidas en CO<sub>2</sub> equivalente (dióxido de carbono equivalente).
<!--https://www.nature.com/articles/s41597-022-01178-9-->

Estos datos están almacenados en una base de datos PostgreSQL con una única tabla, `product_emissions`, que analiza las PCF por producto y por la etapa del proceso de producción en la que se generaron dichas emisiones. Aquí tienes una vista rápida de lo que contiene `product_emissions` en cada columna:

### `product_emissions`

| field                              | data type |
|------------------------------------|-----------|
| `id`                                 | `VARCHAR`   |
| `year`                               | `INT`       |
| `product_name`                       | `VARCHAR`   |
| `company`                            | `VARCHAR`   |
| `country`                            | `VARCHAR`   |
| `industry_group`                     | `VARCHAR`   |
| `weight_kg`                          | `NUMERIC`   |
| `carbon_footprint_pcf`               | `NUMERIC`   |
| `upstream_percent_total_pcf`         | `VARCHAR`   |
| `operations_percent_total_pcf`       | `VARCHAR`   |
| `downstream_percent_total_pcf`       | `VARCHAR`   |

¡Usarás estos datos para analizar la huella de carbono de cada sector de la industria en el conjunto de datos!

In [20]:
-- Update your query here
SELECT *
FROM product_emissions
LIMIT 5;

             id  year  ... operations_percent_total_pcf downstream_percent_total_pcf
0  10056-1-2014  2014  ...                       30.00%                       12.50%
1  10056-1-2015  2015  ...                       30.00%                       12.50%
2  10222-1-2013  2013  ...                       17.36%                        2.01%
3  10261-1-2017  2017  ...                        5.51%                       63.84%
4  10261-2-2017  2017  ...                        4.51%                       70.41%

[5 rows x 11 columns]

In [21]:
select industry_group, 
	count(Distinct Company) as num_companies,
	round(sum(carbon_footprint_pcf),1) as total_industry_footprint
from product_emissions
	where year=(select max(year) from product_emissions)
group by (industry_group)
order by total_industry_footprint desc

                       industry_group  num_companies  total_industry_footprint
0                           Materials              3                  107129.0
1                       Capital Goods              2                   94942.7
2     Technology Hardware & Equipment              4                   21865.1
3            Food, Beverage & Tobacco              1                    3161.5
4  Commercial & Professional Services              1                     740.6
5                 Software & Services              1                     690.0