<center><img src="MKn_Staffelter_Hof.jpeg" alt="Imagen de una empresa antigua"</center>
<!--Image Credit: Martin Kraft https://commons.wikimedia.org/wiki/File:MKn_Staffelter_Hof.jpg -->

La bodega Staffelter Hof es el negocio más antiguo de Alemania, fundada en el año 862 bajo la dinastía carolingia. Ha seguido atendiendo a sus clientes a lo largo de los profundos cambios que ha vivido Europa, como el Sacro Imperio Romano Germánico, el Imperio otomano y las dos guerras mundiales. ¿Qué características permiten que un negocio perdure en el tiempo?

Para ayudar a responder a esta pregunta, BusinessFinancing.co.uk investigó la empresa más antigua que sigue en activo en **casi** todos los países y recopiló los resultados en varios archivos CSV. Este conjunto de datos ya está depurado.

Tener información útil repartida en distintos archivos es un problema común. Aunque para el almacenamiento conviene separar los diferentes tipos de datos, para el análisis querrás tenerlo todo en un mismo lugar. Usarás combinaciones y manipulación de datos para trabajar con este material y comprender mejor cuáles son las empresas más antiguas del mundo.

## Los datos
`businesses` y `new_businesses`
|Column|Description|
|------|-----------|
|`business`|Nombre de la empresa (varchar)|
|`year_founded`|Año de fundación de la empresa (int)|
|`category_code`|Código de la categoría de la empresa (varchar)|
|`country_code`|Código de país ISO 3166-1 de tres letras (char)|
---
`countries`
|Column|Description|
|------|-----------|
|`country_code`|Código de país ISO 3166-1 de tres letras (varchar)|
|`country`|Nombre del país (varchar)|
|`continent`|Nombre del continente en el que se encuentra el país (varchar)|
---
`categories`
|Column|Description|
|------|-----------|
|`category_code`|Código de la categoría de la empresa (varchar)|
|`category`|Descripción de la categoría de la empresa (varchar)|

In [58]:
with h as (
Select  c.continent, min(b.year_founded) as minimo
from countries as c
left join businesses as b
on c.country_code=b.country_code
group by c.continent)
	
Select c.country, c.continent, b.business, b.year_founded
from countries as c
left join businesses as b
using(country_code)
Inner Join h 
on h.continent=c.continent and h.minimo=b.year_founded

     country      continent                     business  year_founded
0  Mauritius         Africa               Mauritius Post          1772
1      Japan           Asia                   Kongō Gumi           578
2    Austria         Europe  St. Peter Stifts Kulinarium           803
3     Mexico  North America  La Casa de Moneda de México          1534
4       Peru  South America      Casa Nacional de Moneda          1565
5  Australia        Oceania               Australia Post          1809

In [59]:
-- How many countries per continent lack data on the oldest businesses

SELECT c.continent, COUNT(c.country_code) AS countries_without_businesses
FROM countries c
LEFT JOIN (
    SELECT * FROM businesses
    UNION ALL
    SELECT * FROM new_businesses
) b
ON c.country_code = b.country_code
WHERE b.business IS NULL
GROUP BY c.continent;

-- Which business categories are best suited to last over the course of centuries?

       continent  countries_without_businesses
0         Africa                             3
1           Asia                             7
2         Europe                             2
3  North America                             5
4        Oceania                            10
5  South America                             3

In [60]:
-- Which business categories are best suited to last over the course of centuries?

Select  c.continent, ca.category, min(b.year_founded) as year_founded
from countries as c
inner join businesses as b
on c.country_code=b.country_code
inner join categories as ca
on ca.category_code=b.category_code	
group by ( c.continent,ca.category)
having c.continent=c.continent
order by c.continent, min(b.year_founded) asc

        continent                           category  year_founded
0          Africa                     Postal Service          1772
1          Africa         Manufacturing & Production          1820
2          Africa               Aviation & Transport          1854
3          Africa                   Food & Beverages          1878
4          Africa                  Banking & Finance          1892
5          Africa  Distillers, Vintners, & Breweries          1933
6          Africa                              Media          1943
7          Africa                        Agriculture          1947
8          Africa                             Mining          1962
9          Africa                             Energy          1968
10           Asia                       Construction           578
11           Asia          Cafés, Restaurants & Bars          1153
12           Asia                   Tourism & Hotels          1584
13           Asia         Manufacturing & Production          1736
14           Asia                     Postal Service          1800
15           Asia                            Defense          1808
16           Asia                   Food & Beverages          1820
17           Asia                  Banking & Finance          1830
18           Asia                       Conglomerate          1841
19           Asia  Distillers, Vintners, & Breweries          1853
20           Asia               Aviation & Transport          1858
21           Asia                             Retail          1883
22           Asia                 Telecommunications          1885
23           Asia                             Mining          1913
24           Asia                             Energy          1928
25           Asia                        Agriculture          1930
26           Asia                              Media          1931
27         Europe          Cafés, Restaurants & Bars           803
28         Europe  Distillers, Vintners, & Breweries           862
29         Europe         Manufacturing & Production           864
30         Europe                        Agriculture          1218
31         Europe                   Tourism & Hotels          1230
32         Europe                             Mining          1248
33         Europe                            Medical          1422
34         Europe                     Postal Service          1520
35         Europe                  Banking & Finance          1606
36         Europe                     Consumer Goods          1649
37         Europe                            Defense          1878
38         Europe                 Telecommunications          1912
39         Europe                              Media          1999
40  North America         Manufacturing & Production          1534
41  North America                        Agriculture          1638
42  North America                             Retail          1670
43  North America  Distillers, Vintners, & Breweries          1703
44  North America                   Tourism & Hotels          1770
45  North America               Aviation & Transport          1870
46  North America                  Banking & Finance          1891
47  North America                              Media          1909
48  North America                   Food & Beverages          1920
49        Oceania                     Postal Service          1809
50        Oceania                  Banking & Finance          1861
51  South America                  Banking & Finance          1565
52  South America         Manufacturing & Production          1621
53  South America                   Food & Beverages          1660
54  South America                            Defense          1811
55  South America          Cafés, Restaurants & Bars          1877