![](image.jpg)

Las personas no solo se endeudan para cubrir necesidades. Un país también puede contraer deuda para gestionar su economía. Por ejemplo, la inversión en infraestructuras es un componente costoso, pero necesario para que la ciudadanía disfrute de una buena calidad de vida. El World Bank es la organización que concede deuda a los países.

En este proyecto, vas a analizar datos de deuda internacional recopilados por el World Bank. El conjunto de datos incluye información sobre el monto de la deuda (en USD) que deben los países en desarrollo en varias categorías. Vas a responder a las siguientes preguntas:

- ¿Cuál es el número de países distintos presentes en la base de datos?
- ¿Qué país tiene el monto de deuda más alto?
- ¿Qué país tiene el nivel más bajo de reembolsos?

A continuación, tienes la descripción de la tabla con la que vas a trabajar:

## `international_debt` table

| Column | Definition | Data Type |
|-|-|-|
|country_name|Nombre del país|`varchar`|
|country_code|Código que representa el país|`varchar`|
|indicator_name|Descripción del indicador de deuda|`varchar`|
|indicator_code|Código que representa el indicador de deuda|`varchar`|
|debt|Valor del indicador de deuda para el país dado (en dólares estadounidenses corrientes)|`float`|

Ejecutarás consultas SQL para responder a tres preguntas, tal como se indica en las instrucciones.

In [12]:
Select count(Distinct country_name) as total_distinct_countries
from international_debt

   total_distinct_countries
0                       124

In [13]:
select country_name, sum(debt) as total_debt
from international_debt
group by country_name
order by total_debt desc
limit 1

  country_name    total_debt
0        China  2.857935e+11

In [14]:
select country_name, indicator_name, sum(debt) as lowest_repayment
from international_debt
where indicator_code = 'DT.AMT.DLXF.CD'
group by country_name, indicator_name
order by lowest_repayment asc
Limit 1

  country_name  ... lowest_repayment
0  Timor-Leste  ...           825000

[1 rows x 3 columns]